import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { Script } from 'node:vm';
import { assetVersion, bundleStyles, versionPageAssets, projectRoot } from '../scripts/assets.mjs';
const text = path => readFile(new URL('../' + path, import.meta.url), 'utf8');
const manifest = JSON.parse(await text('src/manifest.json'));
const main = await text('main.js');
const html = await text('index.html');
const contract = JSON.parse(await text('tests/fixtures/feature-contract.json'));

test('all original DOM integration IDs are preserved', () => {
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
  for (const id of contract.ids) assert.ok(ids.includes(id), `Missing integration target: ${id}`);
  assert.equal(ids.length, new Set(ids).size, 'Duplicate IDs in portal');
});
test('all original function and window entrypoints remain available', () => {
  for (const name of contract.functions) assert.match(main, new RegExp(`(?:async )?function ${name}\\(`));
  for (const name of contract.windowExports) assert.match(main, new RegExp(`window\\.${name}\\s*=`));
});
test('source manifest is unique, ordered and exactly reproduces deployable bundle', async () => {
  assert.equal(manifest.length, new Set(manifest).size);
  const parts = await Promise.all(manifest.map(async path => `// ── src/${path} ──\n${(await text('src/' + path)).trim()}\n`));
  assert.equal(main, '// GENERATED by npm run build. Edit src/ files, not this file.\n' + parts.join('\n'));
  assert.doesNotThrow(() => new Script(main));
});
test('complete stylesheet is bundled in order, without fragile nested imports', async () => {
  const css = await text('styles.css');
  const paths = JSON.parse(await text('src/styles/manifest.json'));
  assert.equal(paths.length, 9);
  assert.equal(paths.at(-1), "mobile.css");
  assert.equal(paths.length, new Set(paths).size);
  assert.equal(css, await bundleStyles());
  assert.doesNotMatch(css, /@import\b/);
  for (const path of paths) assert.ok(css.includes(`src/styles/${path}`));
  const fontUrls = [...css.matchAll(/url\("(assets\/fonts\/[^"?]+)"\)/g)].map(match => match[1]);
  assert.equal(fontUrls.length, 3);
  for (const path of fontUrls) assert.ok((await readFile(new URL(path, projectRoot))).length);
});
test('every page references content-versioned local CSS and JS; rebuilding is stable', async () => {
  const pages = ['index.html', ...(await readdir(new URL('functions/', projectRoot)))
    .filter(path => path.endsWith('.html')).map(path => `functions/${path}`)];
  for (const page of pages) {
    const markup = await text(page);
    const refs = [...markup.matchAll(/<(?:script|link)\b[^>]*?\b(?:src|href)=["']([^"']+)["']/gi)];
    let localAssets = 0;
    for (const match of refs) {
      const reference = match[1].replaceAll('&amp;', '&');
      if (/^(?:https?:|\/\/)/.test(reference)) continue;
      const url = new URL(reference, new URL(page, projectRoot));
      if (!/\.(?:js|css)$/.test(url.pathname)) continue;
      localAssets++;
      assert.equal(url.searchParams.get('v'), assetVersion(await readFile(url)), `${page}: stale asset ${reference}`);
    }
    assert.ok(localAssets >= 2, page);
    assert.equal(await versionPageAssets(page), markup, `${page}: build is not idempotent`);
  }
});
test('standalone tool entrypoints and scripts are retained', async () => {
  for (const name of ['attempt-test', 'batch-timetable', 'classes', 'download-tests', 'test-ids', 'test-schedule', 'watch-recording']) {
    assert.ok((await text(`functions/${name}.html`)).includes('<html'));
    const source = await text(`functions/${name}.js`);
    assert.doesNotThrow(() => new Script(source));
  }
});

test('standalone tool control IDs and shared workbench resources are preserved', async () => {
  const tools = JSON.parse(await text('tests/fixtures/standalone-contract.json'));
  for (const [file, ids] of Object.entries(tools)) {
    const markup = await text(`functions/${file}`);
    for (const id of ids) assert.ok(markup.includes(`id="${id}"`), `${file} missing ${id}`);
    assert.ok(markup.includes('src/styles/workbench.css'));
    assert.ok(markup.includes('src/app/workbench.js'));
    assert.ok(markup.includes(`src/styles/tools/${file.replace('.html', '.css')}`));
    assert.ok(!markup.includes('user-scalable=no'), `${file} must allow mobile zoom`);
  }
  const workbench = await text('src/app/workbench.js');
  assert.doesNotThrow(() => new Script(workbench));
});
