import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const projectRoot = new URL('../', import.meta.url);
export const assetVersion = contents => createHash('sha256').update(contents).digest('hex').slice(0, 12);

// Keep the source styles modular, but deliver a single complete stylesheet.
// Relative font/image URLs must be resolved from the output, not each source file.
export async function bundleStyles() {
  const manifest = JSON.parse(await readFile(new URL('src/styles/manifest.json', projectRoot), 'utf8'));
  const output = new URL('styles.css', projectRoot);
  const parts = await Promise.all(manifest.map(async path => {
    const sourceUrl = new URL(`src/styles/${path}`, projectRoot);
    let source = await readFile(sourceUrl, 'utf8');
    if (/@import\b/i.test(source)) throw new Error(`Nested CSS imports are not supported: ${path}`);
    source = source.replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/g, (match, quote, value) => {
      const asset = value.trim();
      if (/^(?:[a-z][a-z\d+.-]*:|\/|#)/i.test(asset)) return match;
      const resolved = new URL(asset, sourceUrl);
      const rebased = relative(dirname(fileURLToPath(output)), fileURLToPath(resolved)).split(sep).join('/');
      return `url("${rebased}${resolved.search}${resolved.hash}")`;
    });
    return `/* ── src/styles/${path} ── */\n${source.trim()}\n`;
  }));
  return '/* GENERATED by npm run build. Edit src/styles/ files, not this file. */\n' + parts.join('\n');
}

// New markup must never be paired with a browser's cached, incompatible bundle.
// Query fingerprints work on static hosts without duplicating generated files.
export async function versionPageAssets(path) {
  const pageUrl = new URL(path, projectRoot);
  const html = await readFile(pageUrl, 'utf8');
  const pattern = /(<(?:script|link)\b[^>]*?\b(?:src|href)\s*=\s*)(["'])([^"']+)\2/gi;
  const replacements = await Promise.all([...html.matchAll(pattern)].map(async match => {
    const reference = match[3].replaceAll('&amp;', '&');
    if (/^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(reference)) return match[0];
    const url = new URL(reference, pageUrl);
    if (!/\.(?:js|css)$/.test(url.pathname)) return match[0];
    if (!url.href.startsWith(projectRoot.href)) throw new Error(`Asset outside project: ${reference}`);
    const contents = await readFile(url);
    const params = new URLSearchParams(url.search);
    params.set('v', assetVersion(contents));
    const versioned = `${reference.split(/[?#]/)[0]}?${params}${url.hash}`.replaceAll('&', '&amp;');
    return `${match[1]}${match[2]}${versioned}${match[2]}`;
  }));
  let index = 0;
  return html.replace(pattern, () => replacements[index++]);
}
