import { readFile, writeFile, readdir } from 'node:fs/promises';
import { Script } from 'node:vm';
import { bundleStyles, versionPageAssets } from './assets.mjs';
const root = new URL('../', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('src/manifest.json', root), 'utf8'));
const parts = await Promise.all(manifest.map(async path => {
  const source = await readFile(new URL(`src/${path}`, root), 'utf8');
  return `// ── src/${path} ──\n${source.trim()}\n`;
}));
// Preserve the shared classic-script scope used by existing inline handlers and
// standalone tools. Feature ordering is explicit rather than incidental.
const output = '// GENERATED by npm run build. Edit src/ files, not this file.\n' + parts.join('\n');
new Script(output, { filename: 'main.js' });
await writeFile(new URL('main.js', root), output);
await writeFile(new URL('styles.css', root), await bundleStyles());
const pages = ['index.html', ...(await readdir(new URL('functions/', root)))
  .filter(path => path.endsWith('.html')).map(path => `functions/${path}`)];
for (const page of pages) {
  await writeFile(new URL(page, root), await versionPageAssets(page));
}
// Inline the tiny appearance bootstrap: no extra request and no wait for auth/CDNs.
const boot = (await readFile(new URL('src/app/theme-boot.js', root), 'utf8')).trim();
new Script(boot, { filename: 'theme-boot.js' });
const indexPath = new URL('index.html', root);
let index = await readFile(indexPath, 'utf8');
const block = `<!-- appearance-boot:start -->\n<script>${boot}</script>\n<!-- appearance-boot:end -->`;
index = index.includes('<!-- appearance-boot:start -->')
  ? index.replace(/<!-- appearance-boot:start -->[\s\S]*?<!-- appearance-boot:end -->/, () => block)
  : index.replace('    <link rel="icon"', `${block}\n    <link rel="icon"`);
if (!index.includes('portalAppearance.apply(document.body)')) {
  index = index.replace(/(<body[^>]*>)/, '$1\n    <script>portalAppearance.apply(document.body);</script>');
}
await writeFile(indexPath, index);
console.log(`Built main.js from ${manifest.length} feature sources, bundled styles.css, and versioned assets in ${pages.length} pages.`);
