import { readFile, writeFile, mkdir, cp, readdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';

export const root = fileURLToPath(new URL('../', import.meta.url));
export async function build({ production = false } = {}) {
  const manifest = JSON.parse(await readFile(path.join(root, 'scripts/manifest.json'), 'utf8'));
  // One classic-script scope preserves the public handler API used by existing pages.
  for (const [key, output] of [['core', 'core.js'], ['scripts', 'main.js'], ['styles', 'styles.css'], ['toolStyles', 'tools.css']]) {
    const parts = await Promise.all(manifest[key].map(async file =>
      `/* Source: ${file} */\n${await readFile(path.join(root, file), 'utf8')}`));
    let content = `/* Generated by npm run build. Edit src/, not this file. */\n${parts.join('\n\n')}`;
    // Retain line endings on the original static distribution files.
    if (['main.js', 'styles.css'].includes(output)) content = content.replace(/\r?\n/g, '\r\n');
    await writeFile(path.join(root, output), content);
  }
  // HTML and its assets must move together between releases. An unversioned URL
  // lets a returning browser reuse the previous UI's stylesheet with new markup.
  const pages = ['index.html', ...(await readdir(path.join(root, 'functions')))
    .filter(name => name.endsWith('.html')).map(name => `functions/${name}`)];
  for (const page of pages) {
    const file = path.join(root, page);
    const html = await readFile(file, 'utf8');
    let updated = html;
    const references = [...html.matchAll(/(?:src|href)="([^"?#]+\.(?:css|js))(?:\?[^"#]*)?"/g)];
    for (const [attribute, url] of references) {
      if (/^(?:https?:)?\/\//.test(url)) continue;
      const asset = await readFile(path.resolve(path.dirname(file), url));
      const revision = createHash('sha256').update(asset).digest('hex').slice(0, 12);
      updated = updated.replace(attribute, attribute.replace(/=".*"$/, `="${url}?v=${revision}"`));
    }
    if (updated !== html) await writeFile(file, updated);
  }
  if (production) {
    const output = path.join(root, 'dist');
    // Removed tools/assets must not survive an incremental production build.
    await rm(output, { recursive: true, force: true });
    await mkdir(output, { recursive: true });
    for (const item of ['_headers', 'index.html', 'main.js', 'core.js', 'styles.css', 'tools.css', 'pseudo_leaderboard.js', 'scraper.js', 'functions', 'models', 'compounds_smiles.json', 'pKa.json', 're.json', 'src/shell', 'assets']) {
      await cp(path.join(root, item), path.join(output, item), { recursive: true });
    }
  }
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await build({ production: true });
  console.log('Built static site → dist/');
}
